# Generated by Django 5.2.17 on 2026-09-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0002_remove_roleassignment_role_assignment_exactly_one_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["product__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="TargetMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. EU, US, UK", max_length=16, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="HardwareRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(help_text="e.g. A, B, Rev2", max_length=50)),
                ("released_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hardware_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="products.hardwarevariant",
                    ),
                ),
            ],
            options={
                "ordering": ["hardware_variant", "label"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orgs.productfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["product_family__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="hardwarevariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hw_variants",
                to="products.product",
            ),
        ),
        migrations.CreateModel(
            name="SoftwareRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("released_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sw_releases",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name", "version"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "software_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.softwarerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["software_release", "name"],
            },
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hardware_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="products.hardwarerevision",
                    ),
                ),
                (
                    "software_options",
                    models.ManyToManyField(
                        blank=True,
                        related_name="configurations",
                        to="products.softwareoption",
                    ),
                ),
                (
                    "software_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configurations",
                        to="products.softwarerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="hardwarevariant",
            name="target_markets",
            field=models.ManyToManyField(
                blank=True, related_name="hw_variants", to="products.targetmarket"
            ),
        ),
        migrations.AddConstraint(
            model_name="hardwarerevision",
            constraint=models.UniqueConstraint(
                fields=("hardware_variant", "label"), name="unique_hw_revision_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("product_family", "slug"), name="unique_product_slug_per_family"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarerelease",
            constraint=models.UniqueConstraint(
                fields=("product", "version"),
                name="unique_sw_release_version_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwareoption",
            constraint=models.UniqueConstraint(
                fields=("software_release", "slug"),
                name="unique_sw_option_slug_per_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="hardwarevariant",
            constraint=models.UniqueConstraint(
                fields=("product", "slug"), name="unique_hw_variant_slug_per_product"
            ),
        ),
    ]
