# Generated by Django 5.2.17 on 2026-09-22 21:33

from django.db import migrations

MARKETS = [
    ("EU", "European Union"),
    ("UK", "United Kingdom"),
    ("US", "United States"),
    ("CA", "Canada"),
]


def seed_markets(apps, schema_editor):
    TargetMarket = apps.get_model("products", "TargetMarket")
    for code, name in MARKETS:
        TargetMarket.objects.get_or_create(code=code, defaults={"name": name})


def remove_seeded_markets(apps, schema_editor):
    TargetMarket = apps.get_model("products", "TargetMarket")
    TargetMarket.objects.filter(code__in=[code for code, _ in MARKETS]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_markets, remove_seeded_markets),
    ]
