# Generated by Django 5.2.17 on 2026-09-24 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_configuration_approved_at_configuration_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softwarerelease",
            options={"ordering": ["product__name", "name", "version"]},
        ),
        migrations.RemoveConstraint(
            model_name="softwarerelease",
            name="unique_sw_release_version_per_product",
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="softwarerelease",
            name="name",
            field=models.CharField(
                default="", help_text="e.g. Firmware, Companion app", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="softwarerelease",
            constraint=models.UniqueConstraint(
                fields=("product", "name", "version"), name="unique_sw_release_version_per_product"
            ),
        ),
    ]
