# Generated by Django 5.2.17 on 2026-10-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_softwarerelease_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarerelease",
            name="target_markets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to use the hardware variant's markets (ADR 0020).",
                related_name="sw_releases",
                to="products.targetmarket",
            ),
        ),
    ]
