# Generated by Django 5.2.17 on 2026-09-22 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("legislation", "Legislation"),
                            ("harmonised_standard", "Harmonised standard"),
                            ("qms", "QMS / internal procedure"),
                            ("customer", "Customer requirement"),
                            ("guidance", "Guidance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("jurisdiction", models.CharField(max_length=16)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("content", models.JSONField()),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Official packages live in version control and are maintainer-reviewed.",
                    ),
                ),
                ("redistributable", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (failed lint or not yet linted)"),
                            ("linted", "Linted clean"),
                            ("fixtures_passed", "Fixtures passed"),
                            ("approved", "Approved / published"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("lint_report", models.JSONField(blank=True, default=list)),
                ("fixture_report", models.JSONField(blank=True, default=list)),
                ("diff_from_previous", models.JSONField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="packages.requirementpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "-imported_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "version"), name="unique_package_version"
                    )
                ],
            },
        ),
    ]
