# Generated by Django 5.2.17 on 2026-09-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementpackage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("requirement", "Requirement (applicability)"),
                    ("method", "Risk method"),
                    ("catalog", "Risk catalog"),
                ],
                default="requirement",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="requirementpackage",
            name="jurisdiction",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Requirement packages only; method/catalog packages aren't market-scoped.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="requirementpackage",
            name="package_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("legislation", "Legislation"),
                    ("harmonised_standard", "Harmonised standard"),
                    ("qms", "QMS / internal procedure"),
                    ("customer", "Customer requirement"),
                    ("guidance", "Guidance"),
                ],
                default="",
                help_text="Requirement packages only; meaningless for method/catalog kinds.",
                max_length=32,
            ),
        ),
    ]
