# Generated by Django 5.2.17 on 2026-10-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0002_requirementpackage_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requirementpackage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("requirement", "Requirement (applicability)"),
                    ("method", "Risk method"),
                    ("catalog", "Risk catalog"),
                    ("question_set", "Shared question set"),
                ],
                default="requirement",
                max_length=16,
            ),
        ),
    ]
