# Generated by Django 5.2.17 on 2026-09-22 21:48

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_seed_target_markets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("stale", models.BooleanField(default=False)),
                (
                    "sod_warning",
                    models.BooleanField(
                        default=False,
                        help_text="Set if approved by someone who also edited an answer in the snapshot, under a 'warn' separation-of-duties policy.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="products.configuration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAnswer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("question_id", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("override_justification", models.TextField(blank=True, default="")),
                (
                    "needs_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Set when carried forward from a previous software release; a reviewer must confirm it actively.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hardware_revision",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.hardwarerevision",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "software_option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.softwareoption",
                    ),
                ),
                (
                    "software_release",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.softwarerelease",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical answer",
                "verbose_name_plural": "historical answers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAssessment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("stale", models.BooleanField(default=False)),
                (
                    "sod_warning",
                    models.BooleanField(
                        default=False,
                        help_text="Set if approved by someone who also edited an answer in the snapshot, under a 'warn' separation-of-duties policy.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.configuration",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical assessment",
                "verbose_name_plural": "historical assessments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_id", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("override_justification", models.TextField(blank=True, default="")),
                (
                    "needs_confirmation",
                    models.BooleanField(
                        default=False,
                        help_text="Set when carried forward from a previous software release; a reviewer must confirm it actively.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hardware_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.hardwarerevision",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.product",
                    ),
                ),
                (
                    "software_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.softwareoption",
                    ),
                ),
                (
                    "software_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="products.softwarerelease",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("hardware_revision__isnull", True),
                                ("product__isnull", False),
                                ("software_option__isnull", True),
                                ("software_release__isnull", True),
                            ),
                            models.Q(
                                ("hardware_revision__isnull", False),
                                ("product__isnull", True),
                                ("software_option__isnull", True),
                                ("software_release__isnull", True),
                            ),
                            models.Q(
                                ("hardware_revision__isnull", True),
                                ("product__isnull", True),
                                ("software_option__isnull", True),
                                ("software_release__isnull", False),
                            ),
                            models.Q(
                                ("hardware_revision__isnull", True),
                                ("product__isnull", True),
                                ("software_option__isnull", False),
                                ("software_release__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="answer_exactly_one_owner",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("product__isnull", False)),
                        fields=("product", "question_id"),
                        name="unique_answer_per_product_question",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("hardware_revision__isnull", False)),
                        fields=("hardware_revision", "question_id"),
                        name="unique_answer_per_hw_revision_question",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("software_release__isnull", False)),
                        fields=("software_release", "question_id"),
                        name="unique_answer_per_sw_release_question",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("software_option__isnull", False)),
                        fields=("software_option", "question_id"),
                        name="unique_answer_per_sw_option_question",
                    ),
                ],
            },
        ),
    ]
