# Generated by Django 5.2.17 on 2026-09-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="override_justification",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required only when this overrides an answer inherited from a broader level. Explain why the override is correct.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="override_justification",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required only when this overrides an answer inherited from a broader level. Explain why the override is correct.",
            ),
        ),
    ]
