# Generated by Django 5.2.17 on 2026-09-23 06:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packages", "0002_requirementpackage_kind_and_more"),
        ("products", "0002_seed_target_markets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalControl",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("implemented", "Implemented"),
                            ("verified", "Verified"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical control",
                "verbose_name_plural": "historical controls",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.configuration",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical risk assessment",
                "verbose_name_plural": "historical risk assessments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("approved", "Approved")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(blank=True, null=True)),
                ("stale", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_assessments",
                        to="products.configuration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("threat", "Threat"),
                            ("hazard", "Hazard"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "violates",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Threats only: the property violated (must be one of the method's properties).",
                        max_length=32,
                    ),
                ),
                ("delta_justification", models.TextField(blank=True, default="")),
                (
                    "source_catalog_entry_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "suggestion_status",
                    models.CharField(
                        choices=[
                            ("custom", "Custom (added manually)"),
                            ("pending", "Suggested, pending review"),
                            ("accepted", "Suggested, accepted"),
                            ("dismissed", "Suggested, dismissed"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("dismissal_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Threats only: the asset this threat targets.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threats",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "base_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this scoped entry overrides that baseline entry for matching configurations.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deltas",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_entries",
                        to="products.product",
                    ),
                ),
                (
                    "scope_hardware_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_entries",
                        to="products.hardwarevariant",
                    ),
                ),
                (
                    "scope_software_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_entries",
                        to="products.softwareoption",
                    ),
                ),
                (
                    "scope_software_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_entries",
                        to="products.softwarerelease",
                    ),
                ),
                (
                    "source_catalog",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "entry_type", "label"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTreatment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("mitigate", "Mitigate"),
                            ("accept", "Accept"),
                            ("transfer", "Transfer"),
                            ("avoid", "Avoid"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "residual_severity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("justification", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="risk.riskentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical treatment",
                "verbose_name_plural": "historical treatments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRiskEntry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("threat", "Threat"),
                            ("hazard", "Hazard"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "violates",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Threats only: the property violated (must be one of the method's properties).",
                        max_length=32,
                    ),
                ),
                ("delta_justification", models.TextField(blank=True, default="")),
                (
                    "source_catalog_entry_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "suggestion_status",
                    models.CharField(
                        choices=[
                            ("custom", "Custom (added manually)"),
                            ("pending", "Suggested, pending review"),
                            ("accepted", "Suggested, accepted"),
                            ("dismissed", "Suggested, dismissed"),
                        ],
                        default="custom",
                        max_length=16,
                    ),
                ),
                ("dismissal_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.product",
                    ),
                ),
                (
                    "scope_hardware_variant",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.hardwarevariant",
                    ),
                ),
                (
                    "scope_software_option",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.softwareoption",
                    ),
                ),
                (
                    "scope_software_release",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="products.softwarerelease",
                    ),
                ),
                (
                    "source_catalog",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Threats only: the asset this threat targets.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "base_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="If set, this scoped entry overrides that baseline entry for matching configurations.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="risk.riskentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical risk entry",
                "verbose_name_plural": "historical risk entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HazardCause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cause_type",
                    models.CharField(
                        choices=[
                            ("hardware_failure", "Hardware failure"),
                            ("software_fault", "Software fault"),
                            ("foreseeable_misuse", "Foreseeable misuse"),
                            ("cyberattack", "Cyberattack"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causes",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hazard_causes",
                        to="risk.riskentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("implemented", "Implemented"),
                            ("verified", "Verified"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controls",
                        to="products.product",
                    ),
                ),
                (
                    "hazard_causes",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="risk.hazardcause"
                    ),
                ),
                (
                    "threats",
                    models.ManyToManyField(
                        blank=True, related_name="controls", to="risk.riskentry"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThreatConsequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "impact_category",
                    models.CharField(
                        choices=[
                            ("safety", "Safety (people)"),
                            ("property_damage", "Property damage"),
                            ("operational", "Operational"),
                            ("financial", "Financial"),
                            ("privacy", "Privacy"),
                        ],
                        max_length=32,
                    ),
                ),
                ("severity", models.PositiveSmallIntegerField()),
                ("severity_is_override", models.BooleanField(default=False)),
                ("override_justification", models.TextField(blank=True, default="")),
                (
                    "hazard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Safety/property-damage consequences link to the hazard entry they cause.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threat_consequences",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consequences",
                        to="risk.riskentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Hazards only; a threat's severity is derived.",
                        null=True,
                    ),
                ),
                ("likelihood", models.PositiveSmallIntegerField()),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="risk.riskentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "method"), name="unique_rating_per_method"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AssetRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.CharField(
                        choices=[
                            ("confidentiality", "Confidentiality"),
                            ("integrity", "Integrity"),
                            ("availability", "Availability"),
                        ],
                        max_length=32,
                    ),
                ),
                ("severity", models.PositiveSmallIntegerField()),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_ratings",
                        to="risk.riskentry",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "method", "property"),
                        name="unique_asset_rating",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("mitigate", "Mitigate"),
                            ("accept", "Accept"),
                            ("transfer", "Transfer"),
                            ("avoid", "Avoid"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "residual_severity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("justification", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="risk.riskentry",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="packages.requirementpackage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entry", "method"), name="unique_treatment_per_method"
                    )
                ],
            },
        ),
    ]
