# Generated by Django 5.2.17 on 2026-09-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roleassignment",
            name="role_assignment_exactly_one_scope",
        ),
    ]
