# Generated by Django 5.2.17 on 2026-09-22 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("orgs", "0002_remove_roleassignment_role_assignment_exactly_one_scope"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroleassignment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to="products.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("organisation__isnull", False),
                        ("product__isnull", True),
                        ("product_family__isnull", True),
                    ),
                    models.Q(
                        ("organisation__isnull", True),
                        ("product__isnull", True),
                        ("product_family__isnull", False),
                    ),
                    models.Q(
                        ("organisation__isnull", True),
                        ("product__isnull", False),
                        ("product_family__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="role_assignment_exactly_one_scope",
            ),
        ),
    ]
